import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';

const apiDefault='http://10.0.2.2:3000/api';
void main()=>runApp(const App());
class App extends StatelessWidget{const App({super.key});Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'A Liga Almoxarifado',theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.blueGrey),home:const Login());}
class Api{static Future<String> base()async{final p=await SharedPreferences.getInstance();return p.getString('api')??apiDefault;}static Future<Map<String,dynamic>> post(String path,Map d)async{final r=await http.post(Uri.parse('${await base()}$path'),headers:{'Content-Type':'application/json'},body:jsonEncode(d));if(r.statusCode>=400)throw Exception(r.body);return jsonDecode(r.body);}static Future<List> get(String path)async{final r=await http.get(Uri.parse('${await base()}$path'));if(r.statusCode>=400)throw Exception(r.body);return jsonDecode(r.body);}static Future<void> patch(String path,Map d)async{final r=await http.patch(Uri.parse('${await base()}$path'),headers:{'Content-Type':'application/json'},body:jsonEncode(d));if(r.statusCode>=400)throw Exception(r.body);}}
class Login extends StatefulWidget{const Login({super.key});State<Login> createState()=>_Login();}
class _Login extends State<Login>{final u=TextEditingController(text:'supervisor'),p=TextEditingController(text:'1234');bool busy=false;String? e;Future<void> go()async{setState(()=>busy=true);try{final x=await Api.post('/login',{'usuario':u.text,'senha':p.text});if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>Home(user:x)));}catch(x){setState(()=>e=x.toString().replaceFirst('Exception: ',''));}finally{if(mounted)setState(()=>busy=false);}}Widget build(BuildContext c)=>Scaffold(body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:420),child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.inventory_2,size:70),const Text('A Liga Almoxarifado',style:TextStyle(fontSize:26,fontWeight:FontWeight.bold)),const SizedBox(height:24),TextField(controller:u,decoration:const InputDecoration(labelText:'Usuário',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:p,obscureText:true,decoration:const InputDecoration(labelText:'Senha',border:OutlineInputBorder())),if(e!=null)Text(e!,style:const TextStyle(color:Colors.red)),const SizedBox(height:12),SizedBox(width:double.infinity,child:FilledButton(onPressed:busy?null:go,child:Text(busy?'Entrando...':'ENTRAR')))]))));}}
class Home extends StatefulWidget{final Map<String,dynamic> user;const Home({super.key,required this.user});State<Home> createState()=>_Home();}
class _Home extends State<Home>{int i=0;List req=[];Future<void> load()async{try{req=await Api.get('/requisicoes?usuario=${Uri.encodeComponent(widget.user['usuario'])}');}catch(_){ }if(mounted)setState((){});}void initState(){super.initState();load();}Widget build(BuildContext c){final admin=widget.user['perfil']=='almoxarifado';return Scaffold(appBar:AppBar(title:Text(admin?'Painel do Almoxarifado':'A Liga Almoxarifado')),body:i==0?(admin?Admin(req:req,reload:load):Solicitar(user:widget.user,reload:load)):(Historico(req:req,user:widget.user,reload:load)),bottomNavigationBar:NavigationBar(selectedIndex:i,onDestinationSelected:(x)=>setState(()=>i=x),destinations:[NavigationDestination(icon:Icon(admin?Icons.dashboard:Icons.add_box),label:admin?'Painel':'Nova'),const NavigationDestination(icon:Icon(Icons.history),label:'Histórico')]));}}
class Solicitar extends StatefulWidget{final Map<String,dynamic> user;final VoidCallback reload;const Solicitar({super.key,required this.user,required this.reload});State<Solicitar> createState()=>_Solicitar();}
class _Solicitar extends State<Solicitar>{final f=GlobalKey<FormState>();final empresa=TextEditingController(),func=TextEditingController(),produto=TextEditingController(),qtd=TextEditingController(text:'1'),tam=TextEditingController(),calc=TextEditingController(),obs=TextEditingController();String tipo='Uniforme';Future<void> send()async{if(!f.currentState!.validate())return;try{final x=await Api.post('/requisicoes',{'empresa':empresa.text,'funcionario':func.text,'tipo':tipo,'produto':produto.text,'quantidade':int.tryParse(qtd.text)??1,'tamanho':tam.text,'calcado':calc.text,'observacoes':obs.text,'solicitante':widget.user['nome'],'usuario':widget.user['usuario']});if(mounted)showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Requisição enviada com sucesso'),content:Text('Nº da requisição: ${x['numero']}\nAguarde a disponibilidade para retirada.'),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('OK'))]));widget.reload();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}}Widget fld(TextEditingController x,String l)=>Padding(padding:const EdgeInsets.only(bottom:12),child:TextFormField(controller:x,decoration:InputDecoration(labelText:l,border:const OutlineInputBorder()),validator:(v)=>v==null||v.trim().isEmpty?'Informe este campo':null));Widget build(BuildContext c)=>SingleChildScrollView(padding:const EdgeInsets.all(16),child:Form(key:f,child:Column(children:[const Align(alignment:Alignment.centerLeft,child:Text('NOVA REQUISIÇÃO',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold))),const SizedBox(height:16),fld(empresa,'Empresa / Condomínio'),fld(func,'Funcionário'),DropdownButtonFormField(value:tipo,decoration:const InputDecoration(labelText:'Tipo',border:OutlineInputBorder()),items:['Uniforme','EPI','Material de Limpeza','Material'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x)=>setState(()=>tipo=x!)),const SizedBox(height:12),fld(produto,'Produto solicitado'),fld(qtd,'Quantidade'),fld(tam,'Tamanho do uniforme'),fld(calc,'Numeração do calçado'),fld(obs,'Observações'),Text('Supervisor/Inspetora: ${widget.user['nome']}'),const SizedBox(height:16),SizedBox(width:double.infinity,height:50,child:FilledButton.icon(onPressed:send,icon:const Icon(Icons.send),label:const Text('ENVIAR REQUISIÇÃO')))])));}}
class Admin extends StatelessWidget{final List req;final VoidCallback reload;const Admin({super.key,required this.req,required this.reload});Future<void> st(String id,String s)async{await Api.patch('/requisicoes/$id',{'status':s});reload();}Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(12),children:[const Text('REQUISIÇÕES RECEBIDAS',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),...req.map((r)=>Card(child:ListTile(title:Text('${r['numero']} • ${r['empresa']}'),subtitle:Text('${r['funcionario']} • ${r['produto']} x${r['quantidade']}\n${r['status']}'),onTap:()=>showDialog(context:c,builder:(_)=>AlertDialog(title:Text('Requisição ${r['numero']}'),content:Text('Empresa: ${r['empresa']}\nFuncionário: ${r['funcionario']}\nProduto: ${r['produto']}\nTamanho: ${r['tamanho']??''}\nQuantidade: ${r['quantidade']}\nResponsável: ${r['solicitante']}'),actions:[if(r['status']=='Pendente')TextButton(onPressed:(){Navigator.pop(c);st(r['id'],'Separando');},child:const Text('SEPARAR')),if(r['status']=='Separando')TextButton(onPressed:(){Navigator.pop(c);st(r['id'],'Disponível para Entrega');},child:const Text('DISPONÍVEL'))]))))]);}}
class Historico extends StatelessWidget{final List req;final Map<String,dynamic> user;final VoidCallback reload;const Historico({super.key,required this.req,required this.user,required this.reload});Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(12),children:req.map((r)=>Card(child:ListTile(title:Text('${r['numero']} - ${r['produto']}'),subtitle:Text('${r['empresa']} | ${r['funcionario']}\n${r['status']}'),trailing:r['status']=='Disponível para Entrega'?const Icon(Icons.draw):null,onTap:r['status']=='Disponível para Entrega'?()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Assinatura(req:r,reload:reload))):null))).toList());}}
class Assinatura extends StatefulWidget{final Map req;final VoidCallback reload;const Assinatura({super.key,required this.req,required this.reload});State<Assinatura> createState()=>_Assinatura();}
class _Assinatura extends State<Assinatura>{final points=<Offset>[];bool busy=false;Future<void> confirm()async{setState(()=>busy=true);try{await Api.patch('/requisicoes/${widget.req['id']}/entrega',{'recebedor':widget.req['funcionario'],'assinatura':jsonEncode(points.map((p)=>[p.dx,p.dy]).toList())});if(mounted){widget.reload();Navigator.pop(context);ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Recebimento confirmado. Requisição entregue.')));}}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}finally{if(mounted)setState(()=>busy=false);}}Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Comprovante de Entrega')),body:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Funcionário: ${widget.req['funcionario']}'),Text('Empresa: ${widget.req['empresa']}'),Text('Produto: ${widget.req['produto']}'),Text('Quantidade: ${widget.req['quantidade']}'),Text('Tamanho: ${widget.req['tamanho']??''}'),const SizedBox(height:18),const Text('Assinatura do funcionário:'),const SizedBox(height:8),Expanded(child:Container(decoration:BoxDecoration(border:Border.all(),borderRadius:BorderRadius.circular(8)),child:GestureDetector(onPanUpdate:(d){setState(()=>points.add(d.localPosition));},onPanEnd:(_){setState(()=>points.add(Offset.infinite));},child:CustomPaint(painter:SigPainter(points))))),Row(children:[TextButton(onPressed:()=>setState(()=>points.clear()),child:const Text('LIMPAR')),const Spacer(),FilledButton(onPressed:busy||points.where((p)=>p!=Offset.infinite).isEmpty?null:confirm,child:Text(busy?'Salvando...':'CONFIRMAR RECEBIMENTO'))])])));}}
class SigPainter extends CustomPainter{final List<Offset> p;SigPainter(this.p);void paint(Canvas c,Size s){final paint=Paint()..strokeWidth=2..strokeCap=StrokeCap.round;for(var i=0;i<p.length-1;i++){if(p[i]!=Offset.infinite&&p[i+1]!=Offset.infinite)c.drawLine(p[i],p[i+1],paint);}}bool shouldRepaint(covariant SigPainter o)=>true;}
