import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';

const apiDefault = 'http://10.0.2.2:3000/api';

void main() => runApp(const AlmoxApp());

class AlmoxApp extends StatelessWidget {
  const AlmoxApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(debugShowCheckedModeBanner:false,title:'A Liga Almoxarifado',theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.blueGrey),home:const LoginPage());
}

class Api {
  static Future<String> base() async { final p=await SharedPreferences.getInstance(); return p.getString('api')??apiDefault; }
  static Future<dynamic> call(String method,String path,[Map<String,dynamic>? data]) async {
    final u=Uri.parse('${await base()}$path'); final h={'Content-Type':'application/json'}; http.Response r;
    if(method=='GET') r=await http.get(u); else if(method=='POST') r=await http.post(u,headers:h,body:jsonEncode(data??{})); else r=await http.patch(u,headers:h,body:jsonEncode(data??{}));
    if(r.statusCode>=400) throw Exception(r.body); return r.body.isEmpty?{}:jsonDecode(r.body);
  }
  static Future<List<dynamic>> list(String path) async => (await call('GET',path)) as List<dynamic>;
}

class LoginPage extends StatefulWidget { const LoginPage({super.key}); @override State<LoginPage> createState()=>_LoginPageState(); }
class _LoginPageState extends State<LoginPage>{
  final u=TextEditingController(text:'supervisor'),s=TextEditingController(text:'1234'),api=TextEditingController(text:apiDefault); bool busy=false; String? erro;
  Future<void> entrar() async { setState(()=>busy=true); try { final p=await SharedPreferences.getInstance(); await p.setString('api',api.text.trim().replaceAll(RegExp(r'\/$'),'')); final user=Map<String,dynamic>.from(await Api.call('POST','/login',{'usuario':u.text.trim(),'senha':s.text})); if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>HomePage(user:user))); } catch(e){if(mounted)setState(()=>erro=e.toString().replaceFirst('Exception: ',''));} finally{if(mounted)setState(()=>busy=false);} }
  @override Widget build(BuildContext c)=>Scaffold(body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:460),child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.inventory_2,size:70),const Text('A Liga Almoxarifado',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),const SizedBox(height:20),TextField(controller:u,decoration:const InputDecoration(labelText:'Usuário',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:s,obscureText:true,decoration:const InputDecoration(labelText:'Senha',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:api,decoration:const InputDecoration(labelText:'Servidor/API',border:OutlineInputBorder())),if(erro!=null)Padding(padding:const EdgeInsets.all(8),child:Text(erro!,style:const TextStyle(color:Colors.red))),SizedBox(width:double.infinity,height:50,child:FilledButton(onPressed:busy?null:entrar,child:Text(busy?'Entrando...':'ENTRAR')))]))));
}

class HomePage extends StatefulWidget { final Map<String,dynamic> user; const HomePage({super.key,required this.user}); @override State<HomePage> createState()=>_HomePageState(); }
class _HomePageState extends State<HomePage>{ int tab=0; List<dynamic> rs=[]; @override void initState(){super.initState();load();}
 Future<void> load() async{try{rs=await Api.list('/requisicoes?usuario=${Uri.encodeComponent(widget.user['usuario'].toString())}');}catch(_){}if(mounted)setState((){});}
 @override Widget build(BuildContext c){final admin=widget.user['perfil']=='almoxarifado';return Scaffold(appBar:AppBar(title:Text(admin?'Painel do Almoxarifado':'Requisição de Almoxarifado')),body:tab==0?(admin?AdminPage(rs:rs,reload:load):RequesterPage(user:widget.user,reload:load)):History(rs:rs),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),destinations:[NavigationDestination(icon:Icon(admin?Icons.dashboard:Icons.add_box),label:admin?'Painel':'Nova'),const NavigationDestination(icon:Icon(Icons.history),label:'Minhas Requisições')]));}
}

const uniformes=['Avental','PP – Calça de Elástico','P – Calça de Elástico','M – Calça de Elástico','G – Calça de Elástico','GG – Calça de Elástico','XG – Calça de Elástico','PP – Calça Portaria','P – Calça Portaria','M – Calça Portaria','G – Calça Portaria','G5 – Calça Portaria','GG – Calça Portaria','XGG – Calça Portaria','PP – Camisa Portaria','P – Camisa Portaria','M – Camisa Portaria','G – Camisa Portaria','G5 – Camisa Portaria','GG – Camisa Portaria','XGG – Camisa Portaria','PP – Camiseta Branca','P – Camiseta Branca','M – Camiseta Branca','G – Camiseta Branca','GG – Camiseta Branca','XG – Camiseta Branca','P – Camiseta Cinza','M – Camiseta Cinza','G – Camiseta Cinza','GG – Camiseta Cinza','XG – Camiseta Cinza','G – Jaqueta'];
const limpeza=['Porta Sabonete Líquido Plast PET 1L Cristal','Álcool Perf. 2L','Mop Pó Acrílico 80x15cm','Copo Descartável 180 ml','Pano Multiuso Rolo 28x25','Papel Higiênico Max Pure 30m LV 12 PG11','Saco de Lixo 80 L','Saco de Lixo 30 L','Esponja Condor c/ Display LV4PG3','Toalha Interfolha Roma 100%','Multiuso 5 L Flotador','Purificador Puro Ar 250 ml Flor Yang','Lustra Móveis Granel 500 ml','Saponáceo Produlimp 1 L'];

class RequesterPage extends StatefulWidget{final Map<String,dynamic> user;final VoidCallback reload;const RequesterPage({super.key,required this.user,required this.reload});@override State<RequesterPage> createState()=>_RequesterPageState();}
class _RequesterPageState extends State<RequesterPage>{final key=GlobalKey<FormState>();final empresa=TextEditingController(),func=TextEditingController(),produto=TextEditingController(),qtd=TextEditingController(text:'1'),tam=TextEditingController(),calc=TextEditingController(),obs=TextEditingController();String tipo='Uniforme';
 List<String> get produtos=>tipo=='Uniforme'?uniformes:tipo=='Material de Limpeza'?limpeza:['Selecionar ou digitar produto'];
 Future<void> enviar()async{if(!key.currentState!.validate())return;try{final r=await Api.call('POST','/requisicoes',{'empresa':empresa.text.trim(),'funcionario':func.text.trim(),'tipo':tipo,'produto':produto.text.trim(),'quantidade':int.tryParse(qtd.text)??1,'tamanho':tam.text.trim(),'calcado':calc.text.trim(),'observacoes':obs.text.trim(),'solicitante':widget.user['nome'],'usuario':widget.user['usuario']});if(mounted)await showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Requisição enviada'),content:Text('Nº ${r['numero']}\nAguarde a disponibilidade para retirada.'),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('OK'))]));widget.reload();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}}
 Widget field(TextEditingController x,String label,{bool req=false})=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextFormField(controller:x,decoration:InputDecoration(labelText:label,border:const OutlineInputBorder()),validator:req?(v)=>v==null||v.trim().isEmpty?'Informe este campo':null:null));
 @override Widget build(BuildContext c)=>SingleChildScrollView(padding:const EdgeInsets.all(16),child:Form(key:key,child:Column(children:[const Align(alignment:Alignment.centerLeft,child:Text('NOVA REQUISIÇÃO',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold))),const SizedBox(height:14),field(empresa,'Empresa / Condomínio',req:true),field(func,'Funcionário',req:true),DropdownButtonFormField<String>(initialValue:tipo,decoration:const InputDecoration(labelText:'Tipo de solicitação',border:OutlineInputBorder()),items:['Uniforme','EPI','Material de Limpeza','Material'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x){setState(()=>tipo=x!);produto.clear();}),const SizedBox(height:10),if(produtos.length>1)DropdownButtonFormField<String>(decoration:const InputDecoration(labelText:'Produto solicitado',border:OutlineInputBorder()),items:produtos.map((x)=>DropdownMenuItem(value:x,child:Text(x,overflow:TextOverflow.ellipsis))).toList(),onChanged:(x)=>produto.text=x??'',validator:(x)=>x==null||x.isEmpty?'Selecione o produto':null)else field(produto,'Produto solicitado',req:true),field(qtd,'Quantidade',req:true),field(tam,'Tamanho do uniforme'),field(calc,'Numeração do calçado'),field(obs,'Observações'),Align(alignment:Alignment.centerLeft,child:Text('Supervisor/Inspetora: ${widget.user['nome']}')),const SizedBox(height:10),SizedBox(width:double.infinity,height:50,child:FilledButton.icon(onPressed:enviar,icon:const Icon(Icons.send),label:const Text('ENVIAR REQUISIÇÃO')))])));
}

class AdminPage extends StatefulWidget{final List<dynamic> rs;final VoidCallback reload;const AdminPage({super.key,required this.rs,required this.reload});@override State<AdminPage> createState()=>_AdminPageState();}
class _AdminPageState extends State<AdminPage>{String filtro='Todos';Future<void> status(String id,String s)async{await Api.call('PATCH','/requisicoes/$id',{'status':s});widget.reload();}
 @override Widget build(BuildContext c){final list=widget.rs.where((r)=>filtro=='Todos'||r['status']==filtro).toList();return Column(children:[SingleChildScrollView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.all(8),child:Row(children:['Todos','Pendente','Separando','Disponível para Entrega','Entregue'].map((x)=>Padding(padding:const EdgeInsets.only(right:6),child:ChoiceChip(label:Text(x),selected:filtro==x,onSelected:(_)=>setState(()=>filtro=x))).toList())),Expanded(child:RefreshIndicator(onRefresh:()async=>widget.reload(),child:ListView(padding:const EdgeInsets.all(10),children:[Text('REQUISIÇÕES RECEBIDAS: ${list.length}',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),...list.map((r)=>Card(child:ListTile(leading:Icon(r['status']=='Entregue'?Icons.check_circle:Icons.inventory_2),title:Text('${r['numero']} • ${r['empresa']}'),subtitle:Text('${r['funcionario']} • ${r['tipo']} • ${r['produto']} x${r['quantidade']}\n${r['status']}'),onTap:()=>showModalBottomSheet(context:c,builder:(_)=>Padding(padding:const EdgeInsets.all(20),child:Wrap(children:[Text('REQUISIÇÃO ${r['numero']}',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:12),Text('Empresa: ${r['empresa']}\nFuncionário: ${r['funcionario']}\nResponsável: ${r['solicitante']}\nProduto: ${r['produto']}\nTamanho: ${r['tamanho']??''}\nQuantidade: ${r['quantidade']}'),const SizedBox(height:12),if(r['status']=='Pendente')FilledButton.icon(onPressed:(){Navigator.pop(c);status(r['id'].toString(),'Separando');},icon:const Icon(Icons.inventory),label:const Text('SEPARADO / INICIAR SEPARAÇÃO')),if(r['status']=='Separando')FilledButton.icon(onPressed:(){Navigator.pop(c);status(r['id'].toString(),'Disponível para Entrega');},icon:const Icon(Icons.check_box),label:const Text('DISPONÍVEL PARA ENTREGA'))]))))])))]));}
}

class History extends StatelessWidget{final List<dynamic> rs;const History({super.key,required this.rs});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(12),children:[const Text('HISTÓRICO',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),...rs.map((r)=>Card(child:ListTile(title:Text('${r['numero']} • ${r['produto']}'),subtitle:Text('Empresa: ${r['empresa']}\nFuncionário: ${r['funcionario']}\nQtd: ${r['quantidade']} | Status: ${r['status']}\nSolicitado por: ${r['solicitante']}\nEntrega: ${r['entrega']?['data']??'-'}'))))]);}

class SignaturePage extends StatefulWidget{final Map<String,dynamic> r;const SignaturePage({super.key,required this.r});@override State<SignaturePage> createState()=>_SignaturePageState();}
class _SignaturePageState extends State<SignaturePage>{List<Offset?> pts=[];bool busy=false;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Comprovante de Entrega')),body:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Funcionário: ${widget.r['funcionario']}'),Text('Empresa: ${widget.r['empresa']}'),Text('Produto: ${widget.r['produto']} | Qtd: ${widget.r['quantidade']}'),Text('Tamanho: ${widget.r['tamanho']??''}'),const SizedBox(height:15),const Text('Assinatura do recebimento:',style:TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:8),Expanded(child:Container(decoration:BoxDecoration(border:Border.all(),borderRadius:BorderRadius.circular(8)),child:GestureDetector(onPanStart:(d)=>setState(()=>pts.add(d.localPosition)),onPanUpdate:(d)=>setState(()=>pts.add(d.localPosition)),onPanEnd:(_)=>setState(()=>pts.add(null)),child:CustomPaint(painter:SigPainter(pts),child:const SizedBox.expand())))),Row(children:[TextButton(onPressed:()=>setState(()=>pts=[]),child:const Text('LIMPAR')),const Spacer(),FilledButton(onPressed:busy||pts.whereType<Offset>().isEmpty?null:confirmar,child:Text(busy?'Salvando...':'CONFIRMAR RECEBIMENTO'))])])));
 Future<void> confirmar()async{setState(()=>busy=true);try{await Api.call('PATCH','/requisicoes/${widget.r['id']}/entrega',{'recebidoPor':widget.r['funcionario'],'assinatura':jsonEncode(pts.map((p)=>p==null?null:[p.dx,p.dy]).toList())});if(mounted)Navigator.pop(c,true);}catch(e){if(mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(e.toString())));}finally{if(mounted)setState(()=>busy=false);}}
}
class SigPainter extends CustomPainter{final List<Offset?> pts;SigPainter(this.pts);@override void paint(Canvas c,Size s){final p=Paint()..strokeWidth=2.5..strokeCap=StrokeCap.round;for(int i=1;i<pts.length;i++){if(pts[i-1]!=null&&pts[i]!=null)c.drawLine(pts[i-1]!,pts[i]!,p);}}@override bool shouldRepaint(covariant SigPainter old)=>old.pts!=pts;}
